import React, {useState} from "react";
import s from "./Header.module.css";

import enFlag from "../../public/img/icons/Header/enFlag.svg";
import burger from "../../public/img/icons/Header/burger.svg";
import closeNav from "../../public/img/icons/Header/close.svg";

import Image from "next/image";
import Head from "next/head";
import Link from "next/link";

const Header: React.FC = ( {} ): JSX.Element => {

    const [navActive, setNavActive] = useState<boolean> ( false )

    return (
        <>
            <Head>
                <title>Software</title>
                <meta name="description" content="Generated by create next app"/>
                {/* <link type="image/svg" sizes="120x120" rel="icon" href="" /> */}
            </Head>
            <header className={s.wrapper}>
                <div className={s.container}>
                    <div className={s.header_inner}>
                        <Link href="/">
                            <a className={s.logo}>Software Logo</a>
                        </Link>
                        <div className={s.finder}>
                            <input className={s.find_input} placeholder="Search..."/>
                            <div className={s.lang_switcher}>
                                <Image src={enFlag} alt="EN" width={24} height={14}/>
                                <span className={s.lang_text}>EN</span>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <header className={s.mobile_wrapper}>
                <div className={s.container}>
                    <div className={s.mob_header_inner}>
                        <div className={s.def_inner}>
                            <Link href="/">
                                <a className={s.logo}>Software Logo</a>
                            </Link>
                            <div className={s.burger_wrapper} onClick={() => setNavActive ( true )}>
                                <Image src={burger} width={30} height={30}/>
                            </div>
                        </div>
                    </div>
                </div>

                <div className={navActive ? `${s.mob_finder_wrapper} ${s.finder_active}` : s.mob_finder_wrapper}>
                    <div className={s.mob_finder}>
                        <input className={s.find_input} placeholder="Search..."/>
                        <div className={s.lang_switcher}>
                            <Image src={enFlag} alt="EN" width={24} height={14}/>
                            <span className={s.lang_text}>EN</span>
                        </div>
                    </div>
                    <div className={s.mob_nav}>
                        <Link href="/">
                            <a className={s.mob_nav_link}>Home Page</a>
                        </Link>
                        <Link href="/help">
                            <a className={s.mob_nav_link}>Help</a>
                        </Link>
                        <Link href="/terms">
                            <a className={s.mob_nav_link}>ToF</a>
                        </Link>
                    </div>
                    <div className={s.nav_close} onClick={() => setNavActive ( false )}>
                        <Image src={closeNav} width={30} height={30}/>
                    </div>
                </div>
            </header>
        </>
    );
};

export default Header;