// @ts-nocheck
import React, {FC, useState} from "react";
import s from "./Header.module.css";
import burger from "../../public/img/icons/Header/burger.svg";
import closeNav from "../../public/img/icons/multiply-3-24.png";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import RootWrapper from "../RootWrapper/RootWrapper";
import {useAppDispatch, useAppSelector} from "../../hooks/useTypedSelector";
import {changeSortString} from "../../store/slices/productsSlice";
import {useHistory} from "../../hooks/historyProvider";
import {useRouter} from "next/router";

const Header: FC<IHeaderProps> = (): JSX.Element => {
    const [navActive, setNavActive] = useState<boolean> ( false );
    const searchString = useAppSelector ( state => state.productsSlice.searchString )
    const config = useAppSelector ( state => state.configSlice.config )
    const bgColor = config.colors.headerColor
    const dispatch = useAppDispatch ()
    const {history} = useHistory ()
    const router = useRouter ()
    const onChangeHandler = ( e ) => {
        dispatch ( changeSortString ( e.target.value ) )
        if (history[history.length - 1] == '/help' || history[history.length - 1] == '/terms') router.push ( '/' )
    }
    const borderColor = useAppSelector ( state => state.configSlice.config.colors.blockBorderColor )
    const styles = {
        border: `1px solid ${borderColor}`,
    };
    return (
        <>
            <Head>
                <title>Software</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <RootWrapper headerBg>
                <header className={s.wrapper}>
                    <div className={s.container}>
                        <div className={s.header_inner}>
                            <Link href="/">
                                <img src={config.siteLogo} alt={''} className={s.logo}/>
                            </Link>
                            <div className={s.finder}>
                                <input onChange={onChangeHandler} value={searchString ? searchString : ''}
                                       className={s.find_input} style={styles} placeholder="Search..."/>
                            </div>
                        </div>
                    </div>
                </header>
            </RootWrapper>

            <RootWrapper headerBg>
                <header className={s.mobile_wrapper}>
                    <div className={s.container}>
                        <div className={s.mob_header_inner}>
                            <div className={s.def_inner}>
                                <Link href="/">
                                    <img src={config.siteLogo} alt={''} className={s.logo}/>
                                </Link>
                                <div className={s.burger_wrapper} onClick={() => setNavActive ( true )}>
                                    <Image src={burger} width={30} height={30}/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div
                        className={navActive ? `${s.mob_finder_wrapper} ${s.finder_active}` : s.mob_finder_wrapper}
                        style={{backgroundColor: bgColor}}>
                        <div className={s.mob_finder}>
                            <input className={s.find_input} style={styles} placeholder="Search..."/>
                        </div>
                        <div className={s.mob_nav}>
                            <Link href="/">
                                <a className={s.mob_nav_link}>Home Page</a>
                            </Link>
                            <Link href="/help">
                                <a className={s.mob_nav_link}>Help</a>
                            </Link>
                            <Link href="/terms">
                                <a className={s.mob_nav_link}>ToF</a>
                            </Link>
                        </div>
                        <div className={s.nav_close} onClick={() => setNavActive ( false )}>
                            <Image src={closeNav} width={16} height={16}/>
                        </div>
                    </div>
                </header>
            </RootWrapper>
        </>
    );
};

export default Header;
